#!/usr/bin/env php
<?php

class SharedData extends Stackable {
    //private $name;
    public function __construct($_name = '') {
        
    }
    public function run(){
        
    }
}

function formatBytes($size, $precision = 2, $useIEC = true)
{
	$suffixes = $useIEC ? array('', 'KiB', 'MiB', 'GiB', 'TiB', 'PiB', 'EiB', 'ZiB', 'YiB') : array('', 'kB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB');  
	$factor = $useIEC ? 1024 : 1000;
	$base = log($size, $factor);

	return round(pow($factor, $base - floor($base)), $precision) . $suffixes[floor($base)];
}

require __DIR__.'/laravact/src/Server.php';

$shared = new SharedData();
$pool = array();
$workers = 2;
for($i = 0; $i < $workers; $i++) {
	$pool[] = new Laravact\Server($shared, 5501 + $i);
	end($pool)->start();
}

require __DIR__.'/bootstrap/autoload.php';

$loop = \React\EventLoop\Factory::create();
$socket = new \React\Socket\Server($loop);
$http = new \React\Http\Server($socket, $loop);
$http->on('request', function ($request, $response) {
	print_r($_FILES);
	$response->writeHead(200, array('Content-Type' => 'text/html'));
	$response->end('<form method="POST"><input name="textr" /><input type="file" name="filer" /><input type="submit" /></form>');
});
$socket->listen(5500, '127.0.0.1');

/*$loop->addPeriodicTimer(3, function() use ($shared) {
	printf('manager : %s %s' . PHP_EOL, formatBytes(memory_get_usage()), formatBytes(memory_get_peak_usage()));
	foreach($shared as $num => $d) {
		printf('server %d: %s %s' . PHP_EOL, $num, formatBytes($d[1]), formatBytes($d[2]));
	}
});*/

$loop->run();
